services:
  - type: web
    name: chinese-dos-games-web
    runtime: python
    buildCommand: |
      git submodule update --init --recursive --remote
      python3 ./static/games/download_data.py
    startCommand: gunicorn app:app
    plan: free